### PR TITLE
put the nav toggling button and the ButtonMenu component inside the n…

### LINKED ISSUE #86: Active list settings bar
Create a settings bar that will display at the top of the page when one list is in view. It will contain items such as:
- [ ] A delete button
- [ ] An edit button (to rename the list)
- [ ] Other things..??

depends on #84

### LINKED ISSUE #110: Nav Button takes up more height than itself
The Nav Button blocks content underneath it with an invisible full-page height.

To reproduce:
1. open the app and create a list
1. try to click the X button of the list

It will be unclickable due to the Nav Button

### PR DESCRIPTION
**Pull request by deefourple**
…ew SettingsBar component

closes #86
closes part of #102
closes #110

### CODE REVIEW

File: src/components/SettingsBar/SettingsBar.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+import PropTypes from 'prop-types'
+
+import NavButton from '../Buttons/NavButton/NavButton'
+import ButtonMenu from '../ButtonMenu/ButtonMenu'
+import { toggleNav } from '../../state/actions'
+
+import ustyle from '../../utils/style'
+import style from './SettingsBar.style.js'
+
+class SettingsBar extends PureComponent {
```
Comment (christopherbot) [inline src/components/SettingsBar/SettingsBar.js]: this can be a functional component

File: src/components/App/App.js [hunk 2]
```diff
@@ -4,7 +4,7 @@ import { connect } from 'react-redux'
 import PropTypes from 'prop-types'
 
 import Nav from '../Nav/Nav'
-import NavButton from '../Buttons/NavButton/NavButton'
+import SettingsBar from "../SettingsBar/SettingsBar"
```
Comment (christopherbot) [inline src/components/App/App.js]: switching from single to double quotes on me are ya

File: src/components/SettingsBar/SettingsBar.js [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+  }
+}
+
+SettingsBar.propTypes = {
+  list: PropTypes.object,
+  isNavOpen : PropTypes.bool,
+}
+
+const mapDispatchToProps = {
+  toggleNav
```
Comment (christopherbot) [inline src/components/SettingsBar/SettingsBar.js]: trailing comma

File: src/components/SettingsBar/SettingsBar.style.js [hunk 4]
```diff
@@ -0,0 +1,7 @@
+import { StyleSheet } from 'react-native'
+
+export default StyleSheet.create({
+  view: {
+    height : 140
```
Comment (christopherbot) [inline src/components/SettingsBar/SettingsBar.style.js]: trailing comma
