### PR TITLE
Dismiss keyboard upon opening + closing the nav

### LINKED ISSUE #182: keyboard remains open when opening the nav
## Steps to reproduce:
1. Get the keyboard to open in the list view by...
a. editing a cell
b. adding a row
c. adding a column
1. Click the nav button to open the nav (note: opening the nav via dragging from the left does not reproduce this bug)

## Expected behaviour
The keyboard goes away

## Current behaviour
The keyboard remains up

## Possible solutions
Each of the components could listen for the nav being opened and toggle their modes back to "not being edited"

### PR DESCRIPTION
**Pull request by deefourple**
closes #182

### CODE REVIEW

File: BotghaniNotepad.js [hunk 1]
```diff
@@ -1,6 +1,12 @@
 import React, { PureComponent } from 'react'
+import { Keyboard } from "react-native"
```
Comment (christopherbot) [inline BotghaniNotepad.js]: " -> '

File: BotghaniNotepad.js [hunk 2]
```diff
@@ -42,6 +48,17 @@ const MainNavigator = createDrawerNavigator({
   drawerWidth: 230, // default is 280
 })
 
+const defaultGetStateForAction = MainNavigator.router.getStateForAction
+MainNavigator.router.getStateForAction = (action, state) => {
+  switch (action.type) {
```
Comment (christopherbot) [inline BotghaniNotepad.js]: this could probably be an `if` statement to be more concise
